version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - 8000:8000
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=champions
      - DB_USERNAME=laravel_admin
      - DB_PASSWORD=laravel_admin
      - DB_CONNECTION=mysql
      - APP_ENV=local
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: champions
      MYSQL_USER: laravel_admin
      MYSQL_PASSWORD: laravel_admin
    volumes:
      - dbdataa:/var/lib/mysql
    ports:
      - "3306:3306"


volumes:
  dbdataa: